swagger: "2.0"
info:
  title: "Prueba Técnica API Flask"
  description: "API que recupera y filtra publicaciones desde un servicio externo."
  version: "1.0.0"
host: "localhost:5000"
basePath: "/"
schemes:
  - "http"
paths:
  /data:
    get:
      summary: "Recuperar publicaciones con un filtro opcional por título."
      description: >
        Este endpoint obtiene publicaciones desde un servicio externo. 
        Permite filtrar publicaciones por título usando un parámetro de consulta opcional.
      parameters:
        - name: "title"
          in: "query"
          description: "Texto para filtrar publicaciones cuyo título sea exactamente este valor."
          required: false
          type: "string"
      responses:
        200:
          description: "Lista de publicaciones, opcionalmente filtradas por título."
          schema:
            type: "array"
            items:
              type: "object"
              properties:
                userId:
                  type: "integer"
                  description: "ID del usuario que creó la publicación."
                id:
                  type: "integer"
                  description: "ID único de la publicación."
                title:
                  type: "string"
                  description: "Título de la publicación."
                body:
                  type: "string"
                  description: "Cuerpo o contenido de la publicación."
        404:
          description: "No se encontraron publicaciones que coincidan exactamente con los criterios de búsqueda."
          schema:
            type: "object"
            properties:
              error:
                type: "string"
                example: "Error Failed to find data"
        500:
          description: "Error del servidor o fallo en la solicitud a la API externa."
          schema:
            type: "object"
            properties:
              error:
                type: "string"
                example: "Error Failed to fetch data"
